import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.GEMINI_API_KEY;

export async function generateBeforeAfterImage(base64Image: string) {
  if (!API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured");
  }

  const ai = new GoogleGenAI({ apiKey: API_KEY });
  
  const prompt = `
Utilize a foto enviada como base.

Crie uma imagem profissional de antes e depois de corpo inteiro, lado a lado.

ESTRUTURA:

• A imagem deve estar dentro de uma moldura elegante e sofisticada.
• Fundo neutro (branco ou cinza claro).
• Antes à esquerda.
• Depois à direita.
• Texto “ANTES” acima da primeira imagem.
• Texto “DEPOIS” acima da segunda imagem.
• No topo central da arte escrever:

EMAGRECENTRO  
Método 4 Fases

ESTILO VISUAL:

• Design clean, premium e minimalista.
• Cores predominantes: branco, dourado metálico (gold) e azul marinho profundo.
• Fonte elegante, sofisticada e clássica (serif).
• Iluminação natural de estúdio fotográfico.
• Corpo inteiro visível dos pés à cabeça.
• Postura levemente melhorada no “depois”.
• Redução realista entre 5% e 10% do peso corporal.
• Abdômen levemente mais definido.
• Sem exageros.
• Rosto 100% fiel ao original.

OBJETIVO:

Transmitir saúde, leveza, confiança e resultado natural.
Visual profissional de clínica estética de alto padrão.
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image.split(',')[1], // Remove data:image/png;base64,
              mimeType: 'image/png',
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image was generated by the AI.");
  } catch (error) {
    console.error("Error generating image:", error);
    throw error;
  }
}
